language: go
sudo: required

go:
  - 1.12.x
  - 1.13.x
  - tip

os:
  - linux

services:
  - docker

env:
  DOCKER_COMPOSE_VERSION: 1.24.1
  GO111MODULE: "on"

before_install:
  - sudo rm /usr/local/bin/docker-compose
  - curl -L https://github.com/docker/compose/releases/download/${DOCKER_COMPOSE_VERSION}/docker-compose-`uname -s`-`uname -m` > docker-compose
  - chmod +x docker-compose
  - sudo mv docker-compose /usr/local/bin

install:
  - go get -u .
  - go fmt ./...
  - CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build -ldflags "-s -w -X main.appVersion=$(git symbolic-ref -q --short HEAD || git describe --tags --exact-match)" -a -installsuffix cgo -o bin/todo-app .
  - docker-compose build

script:
  - ./integration_test.sh

after_success:
  - if [ "$TRAVIS_BRANCH" == "master" ]; then
    docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD";
    docker push johscheuer/todo-app-web;
    fi
