apiVersion: serving.knative.dev/v1alpha1
kind: Service
metadata:
  name: todo-app-web
  namespace: todo-app
spec:
  template:
    spec:
      containers:
      - image: __IMAGE__
        imagePullPolicy: Always
        command: ["./todo-app"]
        args: ["-config-file", "/etc/todo-app/redis.config"]
        volumeMounts:
        - name: todo-app-config
          mountPath: /etc/todo-app
        ports:
        - containerPort: 3000
          name: "http1"
      volumes:
      - name: todo-app-config
        configMap:
          name: todo-app-config
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: todo-app-config
  namespace: todo-app
data:
  redis.config: |-
    {
      "HealthCheckTime": 0,
      "DBDriver": "redis",
      "DBConfig": {
        "master": "redis-master:6379",
        "master-password": "",
        "slave": "redis-slave:6379",
        "slave-password": ""
      }
    }
